name: nearo
description: Nearo - proximity-based social nightlife app built with Flutter and Firebase.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.5.1
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  cloud_functions: ^4.6.8
  firebase_storage: ^11.6.0
  firebase_messaging: ^14.7.9
  firebase_analytics: ^10.8.0
  firebase_crashlytics: ^3.4.8
  firebase_performance: ^0.9.3+8
  google_sign_in: ^6.2.1

  connectivity_plus: ^5.0.2
  network_info_plus: ^4.1.0
  permission_handler: ^11.3.0
  crypto: ^3.0.3
  uuid: ^4.3.3
  intl: ^0.19.0
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
